config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  root 'posts#index', as: 'home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #get '/posts', to:'posts#index', as: :posts
  #get '/posts/new', to:'posts#new', as: :new_post
  #get '/posts/:id', to:'posts#show', as: :post
  #post '/posts', to:'posts#create'
  #get '/posts/:id/edit', to:'posts#edit', as: :edit_post
  #patch '/posts/:id', to:'posts#update'
  #delete '/posts/:id', to:'posts#delete'


  resources :posts do
    resources :comments
  end

  resources :categories

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :posts


  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :account
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys: [:first_name, :last_name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @posts = @category.posts
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:text))
    @comment.account_id = current_account.id
    @comment.post_id = @post.id
    @comment.save
    #@comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end




end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all

    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
    @account = current_account
    @categories = Category.all
  end

  def new
    @post = Post.new()

    @categories = Category.all
  end

  def create
    @categories = Category.all

    @post = Post.new(post_params)
    @post.account_id = current_account.id
    @post.save
    redirect_to @post
  end

  def edit
    @categories = Category.all

    @post = Post.find(params[:id])
  end

  def update
    @categories = Category.all

    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to :post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title,:text,:category_id,:author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
cat index

app/views/categories/show.html.erb
<%= render partial:'layouts/post_list' %>

app/views/layouts/_header.html.erb
<header class="blog-header py-3">

  <div class="row flex-nowrap justify_content_between align-items-center">
    <div class="col-4" >
      <% if account_signed_in?%>
        <p style="margin:auto;font-style:italic;font-size:20px"><%= current_account.full_name %></p>
      <% end %>
    </div>

    <div class="col-4 text-center " style="font-size:32px">
      <span class="blog-header-logo text-dark" href="#">
        <%= link_to 'Simple Blog', home_path, {:style=>'color:#000000;font-weight:bold', :class => "css_class"} %>
      </span>
    </div>

    <div class="float-right col-4 d-flex justify-content-end">
      <% if account_signed_in?%>
        <%= link_to '<button type="button" style="margin-right:10px;" class="btn btn-light">New Post</button>'.html_safe, new_post_path %>
        <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-primary"  %>
      <% else %>
        <%= link_to "Log In", new_account_session_path,class: "btn btn-outline-primary", style: "margin-right:10px;"  %>
        <%= link_to "Sign Up", new_account_registration_path,class: "btn btn-primary"  %>
      <% end %>
    </div>
</header>
<%= render partial: 'layouts/navbar' %>

app/views/layouts/_navbar.html.erb
<div class="nav-scroller py-1 mb-2">
  <nav class="navbar d-flex justify-content-between">
    <%if @categories %>
      <% @categories.each do |category| %>
        <%= link_to category.name, category_path(category.id),{:style=>'color:#000000;'}%>
      <% end %>
    <% end %>
  </nav>
</div>

app/views/layouts/_post_card.html.erb
<div class="card mb-3">
  <div class="card-header"><%= post.category.name %></div>

  <div class="card-body">
    <h3 class="mb-0"><%= link_to post.title, post,{:style=>'color:#000000;'} %></h3>
    <div class="row">
            <div class="col-4 text-muted">Author:  <%= post.account.full_name %></div>
            <div class="col-4 text-muted">Comments: <%= post.comments.count %></div>
            <div class="col-4 text-muted"><%= post.created_at.strftime("%d-%m-%Y") %></div>
    </div>
  </div>
</div>

app/views/layouts/_post_colored_card.html.erb
<div class="card mb-3 border-primary">
  <div class="card-header"><%= post.category.name %></div>

  <div class="card-body">
    <h3 class="mb-0"><%= link_to post.title, post,{:style=>'color:#000000;'} %></h3>
    <div class="row">
            <div class="col-4 text-muted">Author:  <%= post.account.full_name %></div>
            <div class="col-4 text-muted">Comments: <%= post.comments.count %></div>
            <div class="col-4 text-muted"><%= post.created_at.strftime("%d-%m-%Y") %></div>
    </div>
  </div>
</div>

app/views/layouts/_post_list.html.erb
<div class="row mb-2">

  <% @posts.each do |post| %>

    <div class="col-md-6 ">
      <% if account_signed_in?%>
        <% if post.account_id == current_account.id%>
          <%= render partial: 'layouts/post_colored_card', locals: {post: post} %>
        <% else %>
          <%= render partial: 'layouts/post_card', locals: {post: post} %>
        <% end %>
      <% else %>
        <%= render partial: 'layouts/post_card', locals: {post: post} %>
      <% end %>
      </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rail Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

      <%= render partial: 'layouts/header' %>

      <%= yield %>

    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title%>
    <%= f.text_field :title,{class: 'form-control',style: ''}%>
  </div>

  <div class="form-group">
    <%= f.label :text%>
    <%= f.text_area :text,{class: 'form-control',style: ''}%>
  </div>
  <div class="form-group">
    <%= f.label :category_id%>
    <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] },{},{class: 'form-control',style: 'width:20%'}%>
  </div>
  <div class="">
    <%= f.submit 'Submit', class: 'btn btn-primary'%>
  </div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit</h1>
<%= render partial: 'form'%>

app/views/posts/index.html.erb
<%= render partial:'layouts/post_list' %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render partial: 'form'%>

app/views/posts/show.html.erb
<div class="container">
  <div class="container">
    <h1>Post "<%= @post.title %>"</h1>
  </div>
  <div class="container text-muted">
    <p><%= @post.created_at.strftime("%d-%m-%Y") %>
      by
      <%= @post.account.full_name %></p>
  </div>
  <div class="container" style="blog-header">
    <p><%= @post.text %></p>
  </div>
  <div class="container">
    <% if @account %>
      <% if @post.account.id == @account.id%>
        <%= link_to 'Edit', edit_post_path(@post.id) %><br>
        <%= link_to 'Delete', post_path(@post.id), method: :delete%><br>
      <% end %>
    <% end %>

    <%= link_to 'Back to posts', posts_path %><br>
  </div>
  <hr>

  <div class="row">

    <div class="col-6">
      <%= form_for([@post, @post.comments.build]) do |f| %>
        <div class="container">
          <h4>Add comment</h4>
        </div>

        <% if @account %>
          <div class="container">
            <p>Comment<br><%= f.text_area :text, style:'width:100%;height:200px'%></p>
          </div>
          <div class="container">
            <%= f.submit 'Add comment', class: 'btn btn-primary'%>
          </div>
        <% else %>
        <div class="container">
          <p>You need to Log In to add comments</p>
        </div>
        <% end %>
      <% end %>
    </div>

  <div class="col-6">
    <h4>All comments</h4>

    <% @post.comments.each do |comment| %>
      <%if comment.id %>
        <div class="container">
          <div class="no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="p-4 d-flex flex-column position-static">
              <div class="row">
                <div class="col-4 mb-1 text-muted">Author:<%= comment.account.full_name %></div>
              </div>
              <p class="card-text mb-auto"><%= comment.text %></p>
            </div>

            <div class="container">
              <%if @account%>
                <%if @account.id == comment.account_id%>
                  <%if comment.id%>
                    <%= link_to 'Delete Comment', post_comment_path(post_id: comment.post_id, id: comment.id), method: :delete %><br>
                  <% end %>
                <% end %>
              <% end %>
            </div>

          </div>

        </div>
      <% end %>
    <% end %>

  </div>

</div>

</div>